// Auto-generated by generate-types.ts

type Index<T> = T & { __brand: "index" };

type SourceRecord = { slug: Index<string>; raw: string };

export type ShrinesRecord = SourceRecord & {
  ID: string | number;
  総称?: string | null;
  名称: string;
  名称読み?: string | null;
  別名?: string | null;
  都道府県: string;
  区域: string;
  緯度: number;
  経度: number;
  郵便番号?: number | null;
  住所?: string;
  アクセス?: string;
  電話番号?: { 番号?: string; 説明?: string }[];
  祭神?: { ID: string | number; 名称: string }[];
  祭事?: {
    名称: string | number | null;
    日付区分?: string;
    開催月日?: string | null;
    開催月?: number;
    開催月第何週?: number;
    開催月何曜日?: string;
    開始オフセット?: number;
    終了オフセット?: number;
    旧暦?: boolean;
    備考?: string | number | null;
  }[];
};

export type ShrinesCustomIndexKeys = "nameBigram" | "geohash" | "festivalDate";

export type CitiesRecord = SourceRecord & {
  都道府県: string;
  郡?: string | null;
  市区町村: string;
  緯度: number;
  経度: number;
  geohash: string;
};

export type CitiesCustomIndexKeys = "addressBigram";

export type DeitiesRecord = SourceRecord & {
  shrines?: ShrinesRecord[];
  ID: string | number;
  名称: string;
  名称読み?: string;
};

export type DeitiesRelation_shrines = Record<string, string[]>;

export type SourceTypeMap = {
  shrines: ShrinesRecord;
  cities: CitiesRecord;
  deities: DeitiesRecord;
};
